app:
  datasource:
    jdbc-url: "jdbc:postgresql:holidaybooking"
    username: "postgres"
    # todo use an explicit dev profile and prod secrets injection asap
    password: "mysecretpassword"
    pool-size: 10
server:
  servlet:
    contextPath: /api
spring:
  flyway:
    clean-disabled: true
  jmx:
    enabled: true
logging:
  level:
    root: "info"
    org:
      springframework:
        jdbc: "info"
        data: "info"
    org.flywaydb: "info"
    org.hibernate: "info"
    consulting.baxter.holidaybooking: "debug"
#debug: true
